version: '2.19.1'
services:
  app:
    image: node:20-alpine
    container_name: my-profile
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
